SIG_OBS_VALUES = ['DEBOITE', 'ABSENT', 'VIBRE', 'CASSE', 'BLOQUE', 'ENFONCE', 'DESSERRE', 'RAYE', 'LACERE',
                  'INTERRUPTEUR H.S', 'MANQUE', 'ODEUR', 'CLAQUE', 'FERME MAL', 'FONCTIONNE MAL', 'VOYANT ALLUME',
                  'ARRACHE', 'NE FONCTIONNE PAS', 'INSUFFISANT', 'FUITE', 'DUR', 'FUME/CHAUFFE', 'ASPIRER', 'BRUYANT',
                  'DEGONFLE', 'VOYANT HS', 'JEU', 'TAGUE', 'BRUTAL', 'USE/VIDE', 'INTERMITTENT', 'CLIGNOTE', 'BLESSE',
                  'INCOMPLET', 'CALE', 'FAUX CONTACT', 'BALANCE', 'TEMOIN OUVERTURE H.S', 'MAUVAIS', 'A-COUPS',
                  'TIRE A GAUCHE', 'ALLUME', 'CREVE', 'TIRE A DROITE', 'FENDU', 'DEREGLE', 'NE TIRE PAS', 'TORDU',
                  'SALE', 'PATINE', 'REFUSE TITRE', "N'EMET PAS", "N'ENCRE PAS", 'DELOCALISE', 'OUVRE MAL', 'BROUTE',
                  'SECOUSSE', 'TANGUE', 'DECLENCHEMENT']


SIG_ORG_VALUES = ['GLACE/BAIE', 'KLAXON/GONG', 'VOITURE', 'PARE-CHOCS', 'SECURITE PORTE', 'VOLANT',
                  'ECLAIRAGE FEUX EXTERIEURS', 'PANNEAU', 'GIROUETTE MECANISME', 'PORTE', 'BOUTON/ POUSSOIR/ '
                                                                                          'INTERRUPTEUR',
                  'VOYANT ALERTE ORANGE', 'HABILLAGE', 'FREIN EXPLOITATION', 'ESSUIE-GLACE', 'VOYANT ALARME ROUGE',
                  'AIR', 'CLIGNOTANTS/ DETRESSE', 'MOTEUR', 'LUNETTE-AR', 'DEMANDE ARRET', 'ROUE/PNEUMATIQUE',
                  'FEU ANTIBROUILLARD', 'ABS/ASR', 'GIROUETTE ECLAIRAGE', 'LAVE-GLACE', 'RETROVISEUR', 'ECLAIRAGE '
                                                                                                       'INTERIEUR',
                  'RAMPE UFR', 'SELF-SERVICE', 'FREIN DE PARC', 'COMMODO', 'PORTILLON', 'ARTICULATION REMORQUE',
                  'ANNONCEUR VISUEL', 'VIDEO-SURVEILLANCE', 'VENTILATION', 'BOITE VITESSES', 'PURGE PORTE',
                  'VOYANT DE BATTERIE', 'VOYANT ITC', 'FEU CLIGNOTANT', 'EAU', 'HUILE MOTEUR', 'COMMANDE A DISTANCE',
                  'SIEGE VOYAGEUR', 'COMPTAGE VOYAGEURS', 'CAOU.JOINT', 'INFORMATION VOYAGEURS', 'BAGUETTE',
                  'FEU STOP', 'DIRECTION', 'CHAUFFAGE', 'AERATEURS DE TOITURE', 'FREIN A PIED', 'FEU MARCHE AR',
                  'TRAPPE GAZ', 'ARRET URGENCE', 'BRUITEUR', 'PARE-BRISE', 'SUSPENSION', 'POIGNEE', 'DEMARRAGE',
                  'CARBURANT', 'PEDALE DE FREIN', 'ECHAPPEMENT', 'BARRE', 'TEMOIN DIAGNOSTIC', 'FEU GABARIT',
                  'ACCELERATEUR ELECTRIQUE', 'TOIT', 'PARE-SOLEIL', 'VIDEO PORTE/MARCHE ARRIERE', 'SIEGE MACH',
                  'ANNONCEUR SONORE', 'MANOMETRE', 'SOUFFLET', 'MICRO', 'PUBLICITE', 'RALENTISSEUR',
                  'PEDALE ACCELERATEUR', 'TIROIR CAISSE', 'COMPTEUR/ TACHYGRAPHE', 'DEGIVRAGE', 'RADIO', 'SYSTEME D '
                                                                                                         'ABAISSEMENT',
                  'ARRET MOTEUR', 'AVTT', 'S A E I V', 'VITESSE', 'BOITIER GESTION MOTEUR', 'PUPITRE.ICS', 'RALENTI',
                  'HUILE DIRECTION', 'MARCHE ARRIERE', 'ALARME DISCRETE', 'MARTEAU BRISE-GLACE', 'EXTINCTEUR',
                  'ACCOUDOIR', 'SELECTEUR AVTT', 'BOITIER POLICE ELECTRONIQUE', 'SELECTEUR VITESSES', 'COMBINE RADIO',
                  'AUTO-RADIO', 'PAPIER BUS', 'DEPART AU PUPITRE PREPOINTAGE', 'COLMATAGE.F.AIR', 'CLOCHE ECOLOGIQUE',
                  'LUBRIMATIC', 'PARE-JAMB.', 'VOYAGEUR', 'HAUT-PARLEUR', 'SIGNALEMENT SUR CARNET', 'PILE BTSAM',
                  'ISSUE SEC.', 'TACHYGRAPHE']

PRED_VARIABLES = ["SYSTEM_N1", "SYSTEM_N2", "SYSTEM_N3", "ODR_LIBELLE", "TYPE_TRAVAIL", "DUREE_TRAVAIL"]